{
 "title": "Confluent Open Source",
 "tags": [
  "kafka",
  "broker",
  "healthcheck"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": "label_values(kafka_server_brokerstate, env)"
   }
  ]
 },
 "panels": [
  {
   "title": "Confluent Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Brokers Online",
     "type": "singlestat",
     "description": "Number of Brokers Online",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count((kafka_server_brokerstate{env=\"$env\"}) == 3 or (kafka_server_brokerstate{env=\"$env\"}) == 4)"
      }
     ]
    },
    {
     "title": "Active Controllers",
     "type": "singlestat",
     "description": "Number of active controllers in the cluster.",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_controller_activecontrollercount{env=\"$env\"})"
      }
     ]
    },
    {
     "title": "Unclean Leader Election Rate",
     "type": "singlestat",
     "description": "Unclean leader election rate",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_controller_stats_uncleanleaderelectionspersec{env=\"$env\"})"
      }
     ]
    },
    {
     "title": "Online Partitions",
     "type": "singlestat",
     "description": "Partitions that are online",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_server_replica_manager_partitioncount{env=\"$env\"})"
      }
     ]
    },
    {
     "title": "Under Replicated Partitions",
     "type": "singlestat",
     "description": "Number of under-replicated partitions (| ISR | < | all replicas |).",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_server_replica_manager_underreplicatedpartitions{env=\"$env\"})"
      }
     ]
    },
    {
     "title": "Offline Partitions Count",
     "type": "singlestat",
     "description": "Number of partitions that don’t have an active leader and are hence not writable or readable.",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_controller_offlinepartitionscount{env=\"$env\"})"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "Aggregated Kafka Broker Pods CPU Usage",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{pod_name=~\"$Release-cp-kafka-(\\\\d+)\"}[5m])) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "description": "Kafka Broker Pods Memory Usage",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{pod_name=~\"$Release-cp-kafka-(\\\\d+)\"}) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "graph",
     "description": "Kafka Broker Pods Disk Usage",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"datadir-$Release-cp-kafka.*\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Byte Rate",
     "type": "graph",
     "description": "Byte Rate",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum( kafka_server_broker_topic_metrics_bytesinpersec{env=\"$env\"})",
       "legendFormat": "Incoming Byte Rate"
      },
      {
       "expr": "sum( kafka_server_broker_topic_metrics_bytesoutpersec{env=\"$env\"})",
       "legendFormat": "Outgoing Byte Rate"
      }
     ]
    },
    {
     "title": "Messages In Per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum( kafka_server_broker_topic_metrics_messagesinpersec{env=\"$env\"})",
       "legendFormat": "{{Messages In Per Second}}"
      }
     ]
    },
    {
     "title": "Produce Request Rate",
     "type": "graph",
     "description": "Produce Request Rate.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum( kafka_server_broker_topic_metrics_totalproducerequestspersec{env=\"$env\"})",
       "legendFormat": "Total Produce Request Rate"
      },
      {
       "expr": "sum( kafka_server_broker_topic_metrics_failedproducerequestspersec{env=\"$env\"})",
       "legendFormat": "Failed Produce Request Rate"
      }
     ]
    },
    {
     "title": "Fetch Request Rate",
     "type": "graph",
     "description": "Fetch Request Rate",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum( kafka_server_broker_topic_metrics_totalfetchrequestspersec{env=\"$env\"})",
       "legendFormat": "Fetch Request Rate"
      },
      {
       "expr": "sum(kafka_server_broker_topic_metrics_failedfetchrequestspersec{env=\"$env\"})",
       "legendFormat": "Failed Fetch Request Rate"
      }
     ]
    },
    {
     "title": "Network Processor Avg Idle Percent",
     "type": "graph",
     "description": "Network Processor Avg Idle Percent",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_network_socketserver_networkprocessoravgidlepercent{env=\"$env\"}*100",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Request Handler Avg Idle Percent",
     "type": "graph",
     "description": "Request Handler Avg Idle Percent",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kafka_kafkarequesthandlerpool_requesthandleravgidlepercent{env=\"$env\"}*100",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Confluent Kafka Connect",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Connectors",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "kafka_connnect_worker_metrics_connector_count{env=\"$env\"}"
      }
     ]
    },
    {
     "title": "Connector Startup Success Total",
     "type": "singlestat",
     "description": "The total number of connector starts that succeeded.",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "kafka_connnect_worker_metrics_connector_startup_success_total{env=\"$env\"}"
      }
     ]
    },
    {
     "title": "Connector Startup Failure Total",
     "type": "singlestat",
     "description": "The total number of connector starts that failed.",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "kafka_connnect_worker_metrics_connector_startup_failure_total{env=\"$env\"}"
      }
     ]
    },
    {
     "title": "Number of Tasks",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": " kafka_connnect_worker_metrics_task_count{env=\"$env\"}"
      }
     ]
    },
    {
     "title": "Task Startup Success Total",
     "type": "singlestat",
     "description": "The total number of task starts that succeeded.",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": " kafka_connnect_worker_metrics_task_startup_success_total{env=\"$env\"}"
      }
     ]
    },
    {
     "title": "Task Startup Failure Total",
     "type": "singlestat",
     "description": "The total number of task starts that failed.",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": " kafka_connnect_worker_metrics_task_startup_failure_total{env=\"$env\"}"
      }
     ]
    },
    {
     "title": "Connect Metrics: IO Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " kafka_connnect_metrics_connect_1_io_ratio{env=\"$env\"}"
      }
     ]
    },
    {
     "title": "Connect Metrics: Incoming Byte Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " kafka_connnect_metrics_connect_1_incoming_byte_rate{env=\"$env\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Connect Metrics: Network IO Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " kafka_connnect_metrics_connect_1_network_io_rate{env=\"$env\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Confluent Kafka REST",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Kafka REST servers",
     "type": "singlestat",
     "description": "Number of Kafka REST servers",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count( kafka_rest_jetty_metrics_connections_active{env=\"$env\"})"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "singlestat",
     "description": "Total number of active TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": " kafka_rest_jetty_metrics_connections_active{env=\"$env\"}"
      }
     ]
    },
    {
     "title": "Open Rate",
     "type": "singlestat",
     "description": "The average rate per second of opened TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": " kafka_rest_jetty_metrics_connections_opened_rate{env=\"$env\"}"
      }
     ]
    },
    {
     "title": "Close Rate",
     "type": "singlestat",
     "description": "The average rate per second of closed TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 15, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": " kafka_rest_jetty_metrics_connections_closed_rate{env=\"$env\"}"
      }
     ]
    }
   ]
  },
  { "title": "Confluent KSQL Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "KSQL Metrics: Bytes Consumed",
   "type": "graph",
   "description": "Total number of bytes consumed.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " ksql_server_metrics_bytes_consumed_total{env=\"$env\"}"
    }
   ]
  },
  {
   "title": "KSQL Metrics: Messages Consumed",
   "type": "graph",
   "description": "Messages consumed per second.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " ksql_server_metrics_messages_consumed_per_sec{env=\"$env\"}"
    }
   ]
  },
  {
   "title": "KSQL Metrics: Messages Produced",
   "type": "graph",
   "description": "Messages produced per second.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " ksql_server_metrics_messages_produced_per_sec{env=\"$env\"}"
    }
   ]
  },
  {
   "title": "KSQL Metrics: Active Queries",
   "type": "graph",
   "description": "Number of active queries.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " ksql_server_metrics_num_active_queries{env=\"$env\"}"
    }
   ]
  },
  {
   "title": "KSQL Metrics: Idle Queries",
   "type": "graph",
   "description": "Number of idle queries.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " ksql_server_metrics_num_idle_queries{env=\"$env\"}"
    }
   ]
  },
  {
   "title": "KSQL Metrics: Persistent Queries",
   "type": "graph",
   "description": "Number of persistent queries.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " ksql_server_metrics_num_persistent_queries{env=\"$env\"}"
    }
   ]
  },
  {
   "title": "Confluent Schema Registry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Kafka Schema Registry servers",
     "type": "singlestat",
     "description": "Number of Kafka Schema Registry servers",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count( kafka_schema_registry_jetty_metrics_connections_active{env=\"$env\"})"
      }
     ]
    },
    {
     "title": "Active Connections",
     "type": "singlestat",
     "description": "Total number of active TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 5, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": " kafka_schema_registry_jetty_metrics_connections_active{env=\"$env\"}"
      }
     ]
    },
    {
     "title": "Open Rate",
     "type": "singlestat",
     "description": "The average rate per second of opened TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 10, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": " kafka_schema_registry_jetty_metrics_connections_opened_rate{env=\"$env\"}"
      }
     ]
    },
    {
     "title": "Close Rate",
     "type": "singlestat",
     "description": "The average rate per second of closed TCP connections.",
     "gridPos": { "h": 4, "w": 5, "x": 15, "y": 4 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": " kafka_schema_registry_jetty_metrics_connections_closed_rate{env=\"$env\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Confluent Zookeeper",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Quorum Size",
     "type": "singlestat",
     "description": "Quorum Size of Zookeeper ensemble",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg( zookeeper_quorumsize{env=\"$env\"})"
      }
     ]
    },
    {
     "title": "Alive Connections",
     "type": "singlestat",
     "description": "Number of Alive Connections",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum( zookeeper_numaliveconnections{env=\"$env\"})"
      }
     ]
    },
    {
     "title": "Outstanding Requests",
     "type": "graph",
     "description": "Number of queued requests in the server. This goes up when the server receives more requests than it can process",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " zookeeper_outstandingrequests{env=\"$env\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Number of ZNodes",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "avg( zookeeper_inmemorydatatree_nodecount{env=\"$env\"})"
      }
     ]
    },
    {
     "title": "Number of Watchers",
     "type": "singlestat",
     "description": "Number of Watchers",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum( zookeeper_inmemorydatatree_watchcount{env=\"$env\"})"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "Aggregated Kafka Broker Pods CPU Usage",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate (container_cpu_usage_seconds_total{pod_name=~\"$Release-cp-zookeeper-(\\\\d+)\"}[5m])) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "graph",
     "description": "Kafka Broker Pods Memory Usage",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{pod_name=~\"$Release-cp-zookeeper-(\\\\d+)\"}) by (pod_name)",
       "legendFormat": "{{pod_name}}"
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "graph",
     "description": "Kafka Broker Pods Disk Usage",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"datadir-$Release-cp-zookeeper.*\"}",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    },
    {
     "title": "Request Latency - Minimum",
     "type": "graph",
     "description": "Amount of time it takes for the server to respond to a client request",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": " zookeeper_minrequestlatency{env=\"$env\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Request Latency - Average",
     "type": "graph",
     "description": "Amount of time it takes for the server to respond to a client request",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zookeeper_avgrequestlatency{env=\"$env\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Request Latency - Maximum",
     "type": "graph",
     "description": "Amount of time it takes for the server to respond to a client request",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "zookeeper_maxrequestlatency{env=\"$env\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    }
   ]
  }
 ]
}