{
 "title": "Kafka Connect",
 "tags": [
  "kafka",
  "broker",
  "healthcheck"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(kafka_server_brokerstate, env)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Confluent Kafka Connect", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Connectors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_connect_worker_metrics_connector_count{env=\"$env\"}"
    }
   ]
  },
  {
   "title": "Connector Startup Success Total",
   "type": "singlestat",
   "description": "The total number of connector starts that succeeded.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_connect_worker_metrics_connector_startup_success_total{env=\"$env\"}"
    }
   ]
  },
  {
   "title": "Connector Startup Failure Total",
   "type": "singlestat",
   "description": "The total number of connector starts that failed.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "kafka_connect_worker_metrics_connector_startup_failure_total{env=\"$env\"}"
    }
   ]
  },
  {
   "title": "Number of Tasks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": " kafka_connect_worker_metrics_task_count{env=\"$env\"}"
    }
   ]
  },
  {
   "title": "Task Startup Success Total",
   "type": "singlestat",
   "description": "The total number of task starts that succeeded.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": " kafka_connect_worker_metrics_task_startup_success_total{env=\"$env\"}"
    }
   ]
  },
  {
   "title": "Task Startup Failure Total",
   "type": "singlestat",
   "description": "The total number of task starts that failed.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": " kafka_connect_worker_metrics_task_startup_failure_total{env=\"$env\"}"
    }
   ]
  },
  {
   "title": "Connect Metrics: IO Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " kafka_connect_metrics_connect_1_io_ratio{env=\"$env\"}"
    }
   ]
  },
  {
   "title": "Connect Metrics: Incoming Byte Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " kafka_connect_metrics_connect_1_incoming_byte_rate{env=\"$env\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Connect Metrics: Network IO Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " kafka_connect_metrics_connect_1_network_io_rate{env=\"$env\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}